### ISSUE TITLE
 STATIC DATA MAPPER response 500 after Get Detailed Accommodation.

### ISSUE THREAD

**Issue by wnlstk** [happy-travel/nakijin#401]
Insomnia: Static Data Mapper -> Admin -> Accommodation Managment ->Add Manual Correction To Accommodation

1. Use Add Manual Correction To Accommodation for change hotel name
2. And then route to Accommodation Data Correction.
3. And then route to Get Detailed Accommodation.

Result.
response 500

Expectation.
response  200

**Comment by oleg-n-k** [comment]
Checked on Accommodation_11064467
The endpoints didn't return any errors
![image](https://user-images.githubusercontent.com/36402224/195440539-2bfe7b2e-7c0e-436e-b942-786d69c320b8.png)

**Comment by hasmikharutyunyan** [comment]
not actual
