### ISSUE TITLE
The same synonym can be attached to multiple localities

### ISSUE THREAD

**Issue by wnlstk** [happy-travel/nakijin#449]
DEV

Insomnia -> POST method:

{{ _.mapper.baseUrl }}/api/1.0/admin/locality-candidates/locality-synonyms/move

json body
{"LocalityCandidateIds": [111], "LocalityId": [222]}

Request 200 ok

Next step is:

Insomnia -> POST method:

{{ _.mapper.baseUrl }}/api/1.0/admin/localities/Locality_111/locality-synonyms/Locality_222/move

Request 200 ok

Next step is run updater in mode "Mapping; DataCorrection"

Expectation:
Mapper should work correctly without errors.

Solution:
Add validation to Admin API when adding synonyms

**Comment by hasmikharutyunyan** [comment]
not actual for now
