### ISSUE TITLE
Fix the merging accommodations endpoints (Merge/MergeUncertain).  Deactivated accommodation must store all suppliers code.

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/nakijin#465]
Fix the merging accommodations endpoints (Merge/MergeUncertain).  Deactivated accommodation must store all suppliers code.

**Comment by oleg-n-k** [comment]
POST api/1.0/admin/accommodations/uncertain֊matches/{uncertainMatchId}/merge
POST api/1.0/admin/accommodations/merge

**Comment by nikolaeva31** [comment]
Checked for endpoint `{{baseUrl}}/api/:v/accommodations/:accommodationHtId/detailed-data`. 
There are supplierCodes after merging accommodations.
