### ISSUE TITLE
Add an endpoint for searching by the merge history

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/nakijin#554]
Add an endpoint for searching by the merge history
nakatsu:
POST /api/1.0/accommodations/merge-history/search
mapper:
POST /api/1.0/admin/accommodations/merge-history/search

Request body
{
  "fromDate": "2022-08-25T10:05:36.975Z",
  "toDate": "2022-08-25T10:05:36.975Z",
  "countryCodes": [
    "string"
  ],
  "supplierCodes": [
    "string"
  ],
  "accommodationNameQuery": "string",
  "skip": 0,
  "top": 0
}

**Comment by wnlstk** [comment]
1. nakatsu:
POST /api/1.0/accommodations/merge-history/search -OK ON DEV


2. mapper:
POST /api/1.0/admin/accommodations/merge-history/search - DON"T WORK ON DEV

How to reproduce:
Insomnia -> Nakatsu -> POST Searching by the merge history (mapper)
json body:
{
"fromDate": "2022-07-25T10:05:36.975Z",
"toDate": "2022-08-27T16:05:36.975Z",
"countryCodes": [
"US"
],
"supplierCodes": [
"hotelbookPro"
],
"accommodationNameQuery":"Sheraton Garden Grove Anaheim South",
"skip": 0,
"top": 0
}

-click SEND

Expected result:
- 200 OK 
- 

Actual result:
- 404 NOT FOUND 
{
	"type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
	"title": "Not Found",
	"status": 404,
	"detail": "Not Found",
	"instance": "/api/1.0/admin/accommodations/merge-history/search",
	"spanId": "a2514d05881471ae",
	"traceId": "4093050d7d30a3f105a659ee89b0327d",
	"requestId": "0HMK6IV2T7DAQ:00000003"
}

**Comment by nikolaeva31** [comment]
Delete additional validation 
```
"errors": {
        "SupplierCodes": [
            "'Supplier Codes' must not be empty."
        ]
    }
```
