### ISSUE TITLE
Add an endpoint to unmerge accommodations from uncertain matches

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/nakijin#589]
POST api/1.0/admin/accommodations/merge-history/unmerge/{mergeId}
merge id can be retrieved from the MergeHistory
POST admin/accommodations/merge-history/search

**Comment by nikolaeva31** [comment]
1. curl --request POST 'https://nk-dev.happytravel.com/api/1.0 /accommodations/uncertain-matches/unmerge/b0bbe893-4cce-4ca1-abe1-420063049daa' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer ' \
--data-raw '{
  "mergedAccommodationHtIds": [
    "Accommodation_11085730"
  ]
}'

**AR**: Get error
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
    "title": "Not Found",
    "status": 404,
    "detail": "Not Found",
    "instance": "/api/1.0%20/accommodations/uncertain-matches/unmerge/b0bbe893-4cce-4ca1-abe1-420063049daa",
    "spanId": "71004786a28f0ace",
    "traceId": "dfb18230251607d18722ba2f75452eb3",
    "requestId": "0HMKHM07KVU3Q:00000002"
}
```

**Comment by oleg-n-k** [comment]
the path has been changed to
POST api/1.0/admin/accommodations/merge-history/unmerge/{mergeId}
